apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-sw22
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0008-tenant/tkrw-pr712-0075-0008-app/devfile-sample-sw22@sha256:7ef79ccdaf81b3e9d2fbfb3b28a21dda6426009b69cdf9432ce5a7926e27db16
        name: my-nodejs
        resources: {}
status: {}
